stages:
  - lint-css
  - lint-js
  # - deploy-staging
  - deploy-functionizecli
  # - deploy-production

image: node:9.11.1

lint css:
  stage: lint-css
  before_script:
    - npm install
  cache:
    untracked: true
  only:
    - master
  script:
    - ./node_modules/gulp/bin/gulp.js lint-css

lint js:
  stage: lint-js
  before_script:
    - npm install
  cache:
    untracked: true
    policy: pull
  only:
    - master
  script:
    - ./node_modules/gulp/bin/gulp.js lint-js


# before_script:
#  - apt-get update -qq && apt-get install -y -qq sshpass
#
# Deploy Staging:
#   stage: deploy-staging
#   environment: Staging
#   only:
#     - master
#   script:
#     - sshpass -V
#     - export SSHPASS=$USER_PASS
#     - print $SSHPASS
#     - sshpass -ptoor ssh -o StrictHostKeyChecking=no root@35.192.162.132 "cd /usr/share/nginx/html/staging-gitlab-rvsharma.com && git pull -f"

Functionize-cli Deployment:
  stage: deploy-functionizecli
  script:
    - git clone https://functionize@bitbucket.org/functionize/functionizecli.git /opt/functionizecli
    - cd /opt/functionizecli
    - npm install
    - npm install -g
    - wget -O - https://bitbucket.org/functionize/functionizecli/raw/master/ThirdParty_run.sh | bash

# Deploy Production:
#   stage: deploy-production
#   environment: Production
#   only:
#     - master
#   script:
#     - sshpass -V
#     - export SSHPASS=$USER_PASS
#     - print $SSHPASS
#     - sshpass -ptoor ssh -o StrictHostKeyChecking=no root@35.192.162.132 "cd /usr/share/nginx/html/produc-gitlab-rvsharma.com && git pull -f"
