stages:
  - lint-css
  - lint-js
  - deploy-staging
  - deploy-functionizecli
  - deploy-production

image: node:9.11.1

lint css:
  stage: lint-css
  before_script:
    - npm install
  cache:
    untracked: true
  only:
    - master
  script:
    - ./node_modules/gulp/bin/gulp.js lint-css

lint js:
  stage: lint-js
  cache:
    untracked: true
    policy: pull
  only:
    - master
  script:
    - ./node_modules/gulp/bin/gulp.js lint-js


before_script:
 - apt-get update -qq && apt-get install -y -qq sshpass

Deploy Staging:
  stage: deploy-staging
  environment: Staging
  only:
    - master
  script:
    - sshpass -V
    - export SSHPASS=$USER_PASS
    - print $SSHPASS
    - sshpass -ptoor ssh -o StrictHostKeyChecking=no root@35.192.162.132 "cd /usr/share/nginx/html/staging.rvsharma.com && git pull -f"

Functionize-cli Deployment:
  stage: deploy-functionizecli
  script:
    - git clone https://functionize@bitbucket.org/functionize/functionizecli.git /opt/functionizecli
    - cd /opt/functionizecli
    - npm install
    - npm install -g
    - mv config-sample.js config.js
    - echo "alias functionize-cli='node /opt/functionizecli/functionize.js'" >> ~/.bash_profile
    - source ~/.bash_profile
    - sed -i 's/"xxxxxxxxxx"/"9dd73eb3e026a06c809eaa09cd51fdb5"/g' config.js
    - sed -i 's/"xxxxxx"/"ba3f54fb653e995f15c107ed5d876975"/g' config.js
    - echo "Running Orchestrations"
    - |
      #!/bin/bash
      set +x
      TIMEOUT=3600
      SLEEP=30
      deploy_info=$(/usr/local/bin/functionize run-deployment --depID 6868c7a2bf517501f4ecf65f5d5a84dc)
      if [ $? -ne 0 ]; then
        echo run-deployment failed - $deploy_info; exit 1;
      fi
      run_id=$(echo $deploy_info | sed -n 's:.*runid"\:"\(.*\)"}.*:\1:p')
      echo run_id=$run_id
      echo "Waiting for Test Results"
      if [ "$run_id" != "" ]; then
        start=$(date +'%s')
        while true; do
            result=$(/usr/local/bin/functionize deployment-status-by-runid --runID $run_id)
            if [[ "$result" == *'"Status":"Completed"'* && *'"last_execution_status":"Passed"'* ]]; then
          	   echo -e "\nTest Case Passed";
               break;
            fi
            if [[ "$result" == *'"Status":"Completed"'* && *'"last_execution_status":"Failure"'* ]]; then
          	   echo -e "\nTest Case Failed";
               exit 1;
            fi
            if [ $(($(date +'%s') - $start)) -gt $TIMEOUT ]; then
                echo -e "\nTIMEOUT";
                exit 1;
            fi
          printf "."
          sleep $SLEEP
      done
      fi

Deploy Production:
  stage: deploy-production
  environment: Production
  only:
    - master
  script:
    - sshpass -V
    - export SSHPASS=$USER_PASS
    - print $SSHPASS
    - sshpass -ptoor ssh -o StrictHostKeyChecking=no root@35.192.162.132 "cd /usr/share/nginx/html/rvsharma.com && git pull -f"
