stages:
  - lint-css
  - lint-js
  - unit-test
  - deploy-prod


image: node:9.11.1


lint css:
  stage: lint-css
  before_script:
    - npm install
  cache:
    untracked: true
  only:
    - master
  script:
    - ./node_modules/gulp/bin/gulp.js lint-css

lint js:
  stage: lint-js
  cache:
    untracked: true
    policy: pull
  only:
    - master
  script:
    - ./node_modules/gulp/bin/gulp.js lint-js

run unit test:
  stage: unit-test
  cache:
    untracked: true
    policy: pull
  only:
    - master
  script:
    - ./node_modules/gulp/bin/gulp.js test

before_script:
 - apt-get update -qq && apt-get install -y -qq sshpass

deploy:
  stage: deploy-prod
  environment: Staging
  only:
    - master
  script:
    - sshpass -V
    - export SSHPASS=$USER_PASS
    - print SSHPASS
    - sshpass -e ssh -o StrictHostKeyChecking=no root@35.192.162.132 "cd /usr/share/nginx/html/staging.rvsharma.com && git pull -f"
